Update L2-tests.yml

diff --git a/.github/workflows/L2-tests.yml b/.github/workflows/L2-tests.yml
--- a/.github/workflows/L2-tests.yml
+++ b/.github/workflows/L2-tests.yml
@@ -30,6 +30,7 @@ jobs:
           GH_TOKEN="$GH_TOKEN" gh pr checkout $PR_ID -R siddhesh-chavan-comcast/test_repo
           if [ -f "$REPORT_FILE" ]; then
             echo "Report file $REPORT_FILE found."
+            cp $REPORT_FILE ${{ github.workspace }}/
             break
           else
             echo "Waiting for report file $REPORT_FILE... ($i/30)"
@@ -41,20 +42,20 @@ jobs:
           exit 1
         fi
 
-    - name: Check PR report is ready in test
-      run: |
-        cd ${{ github.workspace }}/test_repo
-        PR_ID="${{ github.event.pull_request.number }}"
-        REPORT_FILE="${{ github.workspace }}/test_repo/test/L2_Tests/reports/r${PR_ID}.txt"
-        if [ -f "$REPORT_FILE" ]; then
-          echo "Report file $REPORT_FILE found."
-        else
-          echo "Report file $REPORT_FILE not found."
-          exit 1
-        fi
+    # - name: Check PR report is ready in test
+    #   run: |
+    #     cd ${{ github.workspace }}/test_repo
+    #     PR_ID="${{ github.event.pull_request.number }}"
+    #     REPORT_FILE="${{ github.workspace }}/test_repo/test/L2_Tests/reports/r${PR_ID}.txt"
+    #     if [ -f "$REPORT_FILE" ]; then
+    #       echo "Report file $REPORT_FILE found."
+    #     else
+    #       echo "Report file $REPORT_FILE not found."
+    #       exit 1
+    #     fi
 
     - name: Upload PR report as artifact
       uses: actions/upload-artifact@v4
       with:
         name: pr_report
-        path: ${{ github.workspace }}/test_repo/test/L2_Tests/reports/r${{ github.event.pull_request.number }}.txt
+        path: ${{ github.workspace }}/r${{ github.event.pull_request.number }}.txt
